spring.application.name=TASK SYSTEM
spring.datasource.url=jdbc:mysql://localhost:3306/tasksystem?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=252252
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=9a4f4c35455ad7622f49478193a93e2b58c573f02b93ad8f3b2a2d4b6a8c1d2e
jwt.expiration=86400000
